### ISSUE TITLE
semi-static does not work with query params

### ISSUE THREAD

**Issue by TinyExplosions** [HenrikJoreteg/semi-static#5]
If I clone this repo, cd into the examples dir and run `node server.js` and open http://localhost:3000/ I see a page, but if I go to http://localhost:3000/?foo=bar it does not work.

Commit e6e8cec7f6d5d4d1cdc3aababde976d260f3d002 seems to have fixed the issue, but it is broken in the current master branch, and in the published version (1.1.1) in npm

**Comment by dead-claudia** [comment]
Fixed.
